spring:
  application:
    name: local-server -> mac
    version: 1.1 version
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://127.0.0.1:3306/local_server?serverTimezone=UTC
    username: root
#    password: 12345678
    password: mysql@zxsmart

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: cn.wxserver.config.typehandler

logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    configs:
      - appId: wx4bcf071e59b1bc01
        secret: f33b1a87686a0ef94e31930e5307ec3e
        token: 111

wechat:
  appId: wx4bcf071e59b1bc01
  appKey: f33b1a87686a0ef94e31930e5307ec3e
  msgMo: vBINVmcddQ-qYoIO64B0a9uNzwdO87rQGJ15417EXHc
  msgAf: vBINVmcddQ-qYoIO64B0a9uNzwdO87rQGJ15417EXHc
  msgEv: vBINVmcddQ-qYoIO64B0a9uNzwdO87rQGJ15417EXHc
server:
  port: 80

baby:
  parameter:
    acquaintance: 2022-08-09
    formal_connect: 2022-08-17 13:30:08
    first_connect: 2022-08-14 01:02:52